using DSharpPlus.Commands.Processors.SlashCommands;
using DSharpPlus.Commands.Processors.SlashCommands.ArgumentModifiers;
using DSharpPlus.Entities;

namespace Acorn.AutoCompleteProviders
{
    internal class ExchangeCommandAutoCompleteProvider : IAutoCompleteProvider
    {
        public ValueTask<IEnumerable<DiscordAutoCompleteChoice>> AutoCompleteAsync(AutoCompleteContext context)
        {
            IEnumerable<DiscordAutoCompleteChoice> mostUsedInput =
                [
                    new DiscordAutoCompleteChoice("Canadian dollars (CAD)", "CAD"),
                    new DiscordAutoCompleteChoice("Costa Rican colóns (CRC)", "CRC"),
                    new DiscordAutoCompleteChoice("Euros (EUR)", "EUR"),
                    new DiscordAutoCompleteChoice("Hungarian forints (HUF)", "HUF"),
                    new DiscordAutoCompleteChoice("Indonesian rupiah (IDR)", "IDR"),
                    new DiscordAutoCompleteChoice("Japanese yen (JPY)", "JPY"),
                    new DiscordAutoCompleteChoice("Kazakhstani tenges (KZT)", "KZT"),
                    new DiscordAutoCompleteChoice("Philippine pesos (PHP)", "PHP"),
                    new DiscordAutoCompleteChoice("United States dollars (USD)", "USD"),
                    new DiscordAutoCompleteChoice("Vietnamese dongs (VND)", "VND")
                ];
            IEnumerable<DiscordAutoCompleteChoice> mostUsedOutput =
                [
                    new DiscordAutoCompleteChoice("Quick Reference – Convert to all currencies relevant in the server", "All"),
                    new DiscordAutoCompleteChoice("Canadian dollars (CAD)", "CAD"),
                    new DiscordAutoCompleteChoice("Costa Rican colóns (CRC)", "CRC"),
                    new DiscordAutoCompleteChoice("Euros (EUR)", "EUR"),
                    new DiscordAutoCompleteChoice("Hungarian forints (HUF)", "HUF"),
                    new DiscordAutoCompleteChoice("Indonesian rupiah (IDR)", "IDR"),
                    new DiscordAutoCompleteChoice("Japanese yen (JPY)", "JPY"),
                    new DiscordAutoCompleteChoice("Kazakhstani tenges (KZT)", "KZT"),
                    new DiscordAutoCompleteChoice("Philippine pesos (PHP)", "PHP"),
                    new DiscordAutoCompleteChoice("United States dollars (USD)", "USD"),
                    new DiscordAutoCompleteChoice("Vietnamese dongs (VND)", "VND")
                ];
            IEnumerable<DiscordAutoCompleteChoice> units =
                [
                    new DiscordAutoCompleteChoice("United Arab Emirates dirham (AED)", "AED"),
                    new DiscordAutoCompleteChoice("Afghan afghani (AFN)", "AFN"),
                    new DiscordAutoCompleteChoice("Armenian dram (AMD)", "AMD"),
                    new DiscordAutoCompleteChoice("Netherlands Antillean guilder (ANG)", "ANG"),
                    new DiscordAutoCompleteChoice("Argentine Peso (ARS)", "ARS"),
                    new DiscordAutoCompleteChoice("Australian dollarydoo (AUD)", "AUD"),
                    new DiscordAutoCompleteChoice("Aruban florin (AWG)", "AWG"),
                    new DiscordAutoCompleteChoice("Azerbaijani manat (AZN)", "AZN"),
                    new DiscordAutoCompleteChoice("Bosnia-Herzegovina convertible marka (BAM)", "BAM"),
                    new DiscordAutoCompleteChoice("Bajan dollar (BBD)", "BBD"),
                    new DiscordAutoCompleteChoice("Bangladeshi taka (BDT)", "BDT"),
                    new DiscordAutoCompleteChoice("Bulgarian lev (BGN)", "BGN"),
                    new DiscordAutoCompleteChoice("Bahraini dinar (BHD)", "BHD"),
                    new DiscordAutoCompleteChoice("Burundian franc (BIF)", "BIF"),
                    new DiscordAutoCompleteChoice("Bermuda dollar (BMD)", "BMD"),
                    new DiscordAutoCompleteChoice("Brunei dollar (BND)", "BND"),
                    new DiscordAutoCompleteChoice("Bolivian boliviano (BOB)", "BOB"),
                    new DiscordAutoCompleteChoice("Brazilian real (BRL)", "BRL"),
                    new DiscordAutoCompleteChoice("Bahamian dollar (BSD)", "BSD"),
                    new DiscordAutoCompleteChoice("Bhutanese ngultrum (BTN)", "BTN"),
                    new DiscordAutoCompleteChoice("Botswana pula (BWP)", "BWP"),
                    new DiscordAutoCompleteChoice("Belarusian ruble (BYN)", "BYN"),
                    new DiscordAutoCompleteChoice("Belize dollar (BZD)", "BZD"),
                    new DiscordAutoCompleteChoice("Canadian dollar (CAD)", "CAD"),
                    new DiscordAutoCompleteChoice("Congolese franc (CDF)", "CDF"),
                    new DiscordAutoCompleteChoice("Swiss franc (CHF)", "CHF"),
                    new DiscordAutoCompleteChoice("Chilean peso (CLP)", "CLP"),
                    new DiscordAutoCompleteChoice("Chinese yuan (onshore) (CNH)", "CNH"),
                    new DiscordAutoCompleteChoice("Chinese yuan (offshore) (CNY)", "CNY"),
                    new DiscordAutoCompleteChoice("Colombian peso (COP)", "COP"),
                    new DiscordAutoCompleteChoice("Costa Rican colón (CRC)", "CRC"),
                    new DiscordAutoCompleteChoice("Cuban peso (CUC)", "CUC"),
                    new DiscordAutoCompleteChoice("Cuban peso (CUP)", "CUP"),
                    new DiscordAutoCompleteChoice("Cape Verdean escudo (CVE)", "CVE"),
                    new DiscordAutoCompleteChoice("Czech koruna (CZK)", "CZK"),
                    new DiscordAutoCompleteChoice("Djiboutian franc (DJF)", "DJF"),
                    new DiscordAutoCompleteChoice("Danish krone (DKK)", "DKK"),
                    new DiscordAutoCompleteChoice("Dominican peso (DOP)", "DOP"),
                    new DiscordAutoCompleteChoice("Algerian dinar (DZD)", "DZD"),
                    new DiscordAutoCompleteChoice("Egyptian pound (EGP)", "EGP"),
                    new DiscordAutoCompleteChoice("Eritrean nakfa (ERN)", "ERN"),
                    new DiscordAutoCompleteChoice("Spanish peseta (ESP)", "ESP"),
                    new DiscordAutoCompleteChoice("Ethiopian birr (ETB)", "ETB"),
                    new DiscordAutoCompleteChoice("euro (EUR)", "EUR"),
                    new DiscordAutoCompleteChoice("Fijian dollar (FJD)", "FJD"),
                    new DiscordAutoCompleteChoice("Falkland Islands pound (FKP)", "FKP"),
                    new DiscordAutoCompleteChoice("French franc (FRF)", "FRF"),
                    new DiscordAutoCompleteChoice("Pound sterling (GBP)", "GBP"),
                    new DiscordAutoCompleteChoice("Georgian lari (GEL)", "GEL"),
                    new DiscordAutoCompleteChoice("Guernsey pound (GGP)", "GGP"),
                    new DiscordAutoCompleteChoice("Ghanaian cedi (GHS)", "GHS"),
                    new DiscordAutoCompleteChoice("Gibraltar pound (GIP)", "GIP"),
                    new DiscordAutoCompleteChoice("Gambian dalasi (GMD)", "GMD"),
                    new DiscordAutoCompleteChoice("Guinean franc (GNF)", "GNF"),
                    new DiscordAutoCompleteChoice("Guatemalan quetzal (GTQ)", "GTQ"),
                    new DiscordAutoCompleteChoice("Guyanese dollar (GYD)", "GYD"),
                    new DiscordAutoCompleteChoice("Hong Kong dollar (HKD)", "HKD"),
                    new DiscordAutoCompleteChoice("Honduran lempira (HNL)", "HNL"),
                    new DiscordAutoCompleteChoice("Haitian gourde (HTG)", "HTG"),
                    new DiscordAutoCompleteChoice("Hungarian forint (HUF)", "HUF"),
                    new DiscordAutoCompleteChoice("Indonesian rupiah (IDR)", "IDR"),
                    new DiscordAutoCompleteChoice("new Israeli shekel (ILS)", "ILS"),
                    new DiscordAutoCompleteChoice("Manx pound (IMP)", "IMP"),
                    new DiscordAutoCompleteChoice("Indian rupee (INR)", "INR"),
                    new DiscordAutoCompleteChoice("Iraqi dinar (IQD)", "IQD"),
                    new DiscordAutoCompleteChoice("Iranian rial (IRR)", "IRR"),
                    new DiscordAutoCompleteChoice("Icelandic króna (ISK)", "ISK"),
                    new DiscordAutoCompleteChoice("Jersey pound (JEP)", "JEP"),
                    new DiscordAutoCompleteChoice("Jamaican dollar (JMD)", "JMD"),
                    new DiscordAutoCompleteChoice("Jordanian dinar (JOD)", "JOD"),
                    new DiscordAutoCompleteChoice("Japanese yen (JPY)", "JPY"),
                    new DiscordAutoCompleteChoice("Kenyan shilling (KES)", "KES"),
                    new DiscordAutoCompleteChoice("Kyrgystani som (KGS)", "KGS"),
                    new DiscordAutoCompleteChoice("Cambodian riel (KHR)", "KHR"),
                    new DiscordAutoCompleteChoice("Comorian franc (KMF)", "KMF"),
                    new DiscordAutoCompleteChoice("North Korean won (KPW)", "KPW"),
                    new DiscordAutoCompleteChoice("South Korean won (KRW)", "KRW"),
                    new DiscordAutoCompleteChoice("Kuwaiti dinar (KWD)", "KWD"),
                    new DiscordAutoCompleteChoice("Cayman Islands dollar (KYD)", "KYD"),
                    new DiscordAutoCompleteChoice("Kazakhstani tenge (KZT)", "KZT"),
                    new DiscordAutoCompleteChoice("Laotian kip (LAK)", "LAK"),
                    new DiscordAutoCompleteChoice("Lebanese pound (LBP)", "LBP"),
                    new DiscordAutoCompleteChoice("Sri Lankan rupee (LKR)", "LKR"),
                    new DiscordAutoCompleteChoice("Liberian dollar (LRD)", "LRD"),
                    new DiscordAutoCompleteChoice("Lesotho loti (LSL)", "LSL"),
                    new DiscordAutoCompleteChoice("Lithuanian litas (LTL)", "LTL"),
                    new DiscordAutoCompleteChoice("Libyan dinar (LYD)", "LYD"),
                    new DiscordAutoCompleteChoice("Moroccan dirham (MAD)", "MAD"),
                    new DiscordAutoCompleteChoice("Moldovan leu (MDL)", "MDL"),
                    new DiscordAutoCompleteChoice("Malagasy ariary (MGA)", "MGA"),
                    new DiscordAutoCompleteChoice("Macedonian denar (MKD)", "MKD"),
                    new DiscordAutoCompleteChoice("Myanmar kyat (MMK)", "MMK"),
                    new DiscordAutoCompleteChoice("Mongolian tugrik (MNT)", "MNT"),
                    new DiscordAutoCompleteChoice("Macanese pataca (MOP)", "MOP"),
                    new DiscordAutoCompleteChoice("Mauritanian ouguiya (MRU)", "MRU"),
                    new DiscordAutoCompleteChoice("Mauritian rupee (MUR)", "MUR"),
                    new DiscordAutoCompleteChoice("Maldivian rufiyaa (MVR)", "MVR"),
                    new DiscordAutoCompleteChoice("Malawian kwacha (MWK)", "MWK"),
                    new DiscordAutoCompleteChoice("Mexican peso (MXN)", "MXN"),
                    new DiscordAutoCompleteChoice("Mexican unidad de inversión (MXV)", "MXV"),
                    new DiscordAutoCompleteChoice("Malaysian ringgit (MYR)", "MYR"),
                    new DiscordAutoCompleteChoice("Mozambican metical (MZN)", "MZN"),
                    new DiscordAutoCompleteChoice("Namibian dollar (NAD)", "NAD"),
                    new DiscordAutoCompleteChoice("Nigerian naira (NGN)", "NGN"),
                    new DiscordAutoCompleteChoice("Nicaraguan córdoba (NIO)", "NIO"),
                    new DiscordAutoCompleteChoice("Norwegian krone (NOK)", "NOK"),
                    new DiscordAutoCompleteChoice("Nepalese rupee (NPR)", "NPR"),
                    new DiscordAutoCompleteChoice("New Zealand dollar (NZD)", "NZD"),
                    new DiscordAutoCompleteChoice("Omani rial (OMR)", "OMR"),
                    new DiscordAutoCompleteChoice("Panamanian balboa (PAB)", "PAB"),
                    new DiscordAutoCompleteChoice("sol (PEN)", "PEN"),
                    new DiscordAutoCompleteChoice("Papua New Guinean kina (PGK)", "PGK"),
                    new DiscordAutoCompleteChoice("Philippine peso (PHP)", "PHP"),
                    new DiscordAutoCompleteChoice("Pakistani rupee (PKR)", "PKR"),
                    new DiscordAutoCompleteChoice("Polish złoty (PLN)", "PLN"),
                    new DiscordAutoCompleteChoice("Portuguese escudo (PTE)", "PTE"),
                    new DiscordAutoCompleteChoice("Paraguayan guarani (PYG)", "PYG"),
                    new DiscordAutoCompleteChoice("Qatari riyal (QAR)", "QAR"),
                    new DiscordAutoCompleteChoice("Romanian leu (RON)", "RON"),
                    new DiscordAutoCompleteChoice("Serbian dinar (RSD)", "RSD"),
                    new DiscordAutoCompleteChoice("Russian ruble (RUB)", "RUB"),
                    new DiscordAutoCompleteChoice("Rwandan franc (RWF)", "RWF"),
                    new DiscordAutoCompleteChoice("Saudi riyal (SAR)", "SAR"),
                    new DiscordAutoCompleteChoice("Solomon Islands dollar (SBD)", "SBD"),
                    new DiscordAutoCompleteChoice("Seychellois rupee (SCR)", "SCR"),
                    new DiscordAutoCompleteChoice("Sudanese pound (SDG)", "SDG"),
                    new DiscordAutoCompleteChoice("Swedish krona (SEK)", "SEK"),
                    new DiscordAutoCompleteChoice("Singapore dollar (SGD)", "SGD"),
                    new DiscordAutoCompleteChoice("Saint Helena pound (SHP)", "SHP"),
                    new DiscordAutoCompleteChoice("Sierra Leonean leone (SLL)", "SLL"),
                    new DiscordAutoCompleteChoice("Somali shilling (SOS)", "SOS"),
                    new DiscordAutoCompleteChoice("Seborgan luigino (SPL)", "SPL"),
                    new DiscordAutoCompleteChoice("Suriname dollar (SRD)", "SRD"),
                    new DiscordAutoCompleteChoice("Sao Tomé and Príncipe dobra (STN)", "STN"),
                    new DiscordAutoCompleteChoice("Syrian pound (SYP)", "SYP"),
                    new DiscordAutoCompleteChoice("Swazi lilangeni (SZL)", "SZL"),
                    new DiscordAutoCompleteChoice("Thai baht (THB)", "THB"),
                    new DiscordAutoCompleteChoice("Tajikistani somoni (TJS)", "TJS"),
                    new DiscordAutoCompleteChoice("Turkmenistani manat (TMT)", "TMT"),
                    new DiscordAutoCompleteChoice("Tunisian dinar (TND)", "TND"),
                    new DiscordAutoCompleteChoice("Turkish lira (TRL)", "TRL"),
                    new DiscordAutoCompleteChoice("Turkish lira (TRY)", "TRY"),
                    new DiscordAutoCompleteChoice("Trinidad & Tobago dollar (TTD)", "TTD"),
                    new DiscordAutoCompleteChoice("Tuvaluan dollar (TVD)", "TVD"),
                    new DiscordAutoCompleteChoice("New Taiwan dollar (TWD)", "TWD"),
                    new DiscordAutoCompleteChoice("Tanzanian shilling (TZS)", "TZS"),
                    new DiscordAutoCompleteChoice("Ukrainian hryvnia (UAH)", "UAH"),
                    new DiscordAutoCompleteChoice("Ugandan shilling (UGX)", "UGX"),
                    new DiscordAutoCompleteChoice("United States dollar (USD)", "USD"),
                    new DiscordAutoCompleteChoice("Uruguayan peso (UYU)", "UYU"),
                    new DiscordAutoCompleteChoice("Uzbekistani som (UZS)", "UZS"),
                    new DiscordAutoCompleteChoice("Venezuelan bolívar (VES)", "VES"),
                    new DiscordAutoCompleteChoice("Vietnamese dong (VND)", "VND"),
                    new DiscordAutoCompleteChoice("Vanuatu vatu (VUV)", "VUV"),
                    new DiscordAutoCompleteChoice("Samoan tala (WST)", "WST"),
                    new DiscordAutoCompleteChoice("Central African CFA franc (XAF)", "XAF"),
                    new DiscordAutoCompleteChoice("silver ounce (XAG)", "XAG"),
                    new DiscordAutoCompleteChoice("gold ounce (XAU)", "XAU"),
                    new DiscordAutoCompleteChoice("East Caribbean dollar (XCD)", "XCD"),
                    new DiscordAutoCompleteChoice("Caribbean guilder (XCG)", "XCG"),
                    new DiscordAutoCompleteChoice("special drawing rights (XDR)", "XDR"),
                    new DiscordAutoCompleteChoice("West African CFA franc (XOF)", "XOF"),
                    new DiscordAutoCompleteChoice("palladium ounce (XPD)", "XPD"),
                    new DiscordAutoCompleteChoice("CFP franc (XPF)", "XPF"),
                    new DiscordAutoCompleteChoice("platinum ounce (XPT)", "XPT"),
                    new DiscordAutoCompleteChoice("Yemeni rial (YER)", "YER"),
                    new DiscordAutoCompleteChoice("South African rand (ZAR)", "ZAR"),
                    new DiscordAutoCompleteChoice("Zambian kwacha (ZMW)", "ZMW"),
                    new DiscordAutoCompleteChoice("Zimbabwe gold (ZWG)", "ZWG")
                ];

            if (context.Parameter.Name == "inputCurrency" && context.UserInput.Length < 2)
            {
                return ValueTask.FromResult(mostUsedInput);
            }
            else if (context.UserInput.Length < 2)
            {
                return ValueTask.FromResult(mostUsedOutput);
            }
            else
            {
                return ValueTask.FromResult(units.Where(unit => unit.Name.ToLower().Contains(context.UserInput.ToLower())).Take(25));
            }
        }
    }
}
