on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: GitHub Releases to Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "2105893"
          username: "Acorn Releases"
          avatar_url: "https://cdn.discordapp.com/icons/1337097452859428874/6dff2743402cabf688c12150c51e6564.png"
          content: "Acorn has been updated. Here is the changelog:"
          reduce_headings: true
